name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install pnpm
      uses: pnpm/action-setup@v2

    - name: vitepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: mpx-ecology/mpxuse
        TARGET_BRANCH: gh_pages
        BUILD_SCRIPT: pnpm i && npm run docs:build
        BUILD_DIR: packages/.vitepress/dist/